// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDevicesCountUsingGETParams creates a new GetDevicesCountUsingGETParams object
// with the default values initialized.
func NewGetDevicesCountUsingGETParams() *GetDevicesCountUsingGETParams {
	var ()
	return &GetDevicesCountUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDevicesCountUsingGETParamsWithTimeout creates a new GetDevicesCountUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDevicesCountUsingGETParamsWithTimeout(timeout time.Duration) *GetDevicesCountUsingGETParams {
	var ()
	return &GetDevicesCountUsingGETParams{

		timeout: timeout,
	}
}

// NewGetDevicesCountUsingGETParamsWithContext creates a new GetDevicesCountUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDevicesCountUsingGETParamsWithContext(ctx context.Context) *GetDevicesCountUsingGETParams {
	var ()
	return &GetDevicesCountUsingGETParams{

		Context: ctx,
	}
}

// NewGetDevicesCountUsingGETParamsWithHTTPClient creates a new GetDevicesCountUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDevicesCountUsingGETParamsWithHTTPClient(client *http.Client) *GetDevicesCountUsingGETParams {
	var ()
	return &GetDevicesCountUsingGETParams{
		HTTPClient: client,
	}
}

/*GetDevicesCountUsingGETParams contains all the parameters to send to the API endpoint
for the get devices count using g e t operation typically these are written to a http.Request
*/
type GetDevicesCountUsingGETParams struct {

	/*TenantID
	  Unique identifier of a tenant.

	*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get devices count using g e t params
func (o *GetDevicesCountUsingGETParams) WithTimeout(timeout time.Duration) *GetDevicesCountUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get devices count using g e t params
func (o *GetDevicesCountUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get devices count using g e t params
func (o *GetDevicesCountUsingGETParams) WithContext(ctx context.Context) *GetDevicesCountUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get devices count using g e t params
func (o *GetDevicesCountUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get devices count using g e t params
func (o *GetDevicesCountUsingGETParams) WithHTTPClient(client *http.Client) *GetDevicesCountUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get devices count using g e t params
func (o *GetDevicesCountUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTenantID adds the tenantID to the get devices count using g e t params
func (o *GetDevicesCountUsingGETParams) WithTenantID(tenantID string) *GetDevicesCountUsingGETParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the get devices count using g e t params
func (o *GetDevicesCountUsingGETParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *GetDevicesCountUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
