// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetP12CertificateUsingGETParams creates a new GetP12CertificateUsingGETParams object
// with the default values initialized.
func NewGetP12CertificateUsingGETParams() *GetP12CertificateUsingGETParams {
	var ()
	return &GetP12CertificateUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetP12CertificateUsingGETParamsWithTimeout creates a new GetP12CertificateUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetP12CertificateUsingGETParamsWithTimeout(timeout time.Duration) *GetP12CertificateUsingGETParams {
	var ()
	return &GetP12CertificateUsingGETParams{

		timeout: timeout,
	}
}

// NewGetP12CertificateUsingGETParamsWithContext creates a new GetP12CertificateUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetP12CertificateUsingGETParamsWithContext(ctx context.Context) *GetP12CertificateUsingGETParams {
	var ()
	return &GetP12CertificateUsingGETParams{

		Context: ctx,
	}
}

// NewGetP12CertificateUsingGETParamsWithHTTPClient creates a new GetP12CertificateUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetP12CertificateUsingGETParamsWithHTTPClient(client *http.Client) *GetP12CertificateUsingGETParams {
	var ()
	return &GetP12CertificateUsingGETParams{
		HTTPClient: client,
	}
}

/*GetP12CertificateUsingGETParams contains all the parameters to send to the API endpoint
for the get p12 certificate using g e t operation typically these are written to a http.Request
*/
type GetP12CertificateUsingGETParams struct {

	/*DeviceID
	  Unique identifier of a device.

	*/
	DeviceID string
	/*TenantID
	  Unique identifier of a tenant.

	*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get p12 certificate using g e t params
func (o *GetP12CertificateUsingGETParams) WithTimeout(timeout time.Duration) *GetP12CertificateUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get p12 certificate using g e t params
func (o *GetP12CertificateUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get p12 certificate using g e t params
func (o *GetP12CertificateUsingGETParams) WithContext(ctx context.Context) *GetP12CertificateUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get p12 certificate using g e t params
func (o *GetP12CertificateUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get p12 certificate using g e t params
func (o *GetP12CertificateUsingGETParams) WithHTTPClient(client *http.Client) *GetP12CertificateUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get p12 certificate using g e t params
func (o *GetP12CertificateUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceID adds the deviceID to the get p12 certificate using g e t params
func (o *GetP12CertificateUsingGETParams) WithDeviceID(deviceID string) *GetP12CertificateUsingGETParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the get p12 certificate using g e t params
func (o *GetP12CertificateUsingGETParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WithTenantID adds the tenantID to the get p12 certificate using g e t params
func (o *GetP12CertificateUsingGETParams) WithTenantID(tenantID string) *GetP12CertificateUsingGETParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the get p12 certificate using g e t params
func (o *GetP12CertificateUsingGETParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *GetP12CertificateUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param deviceId
	if err := r.SetPathParam("deviceId", o.DeviceID); err != nil {
		return err
	}

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
