// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateCustomPropertyForDeviceParams creates a new UpdateCustomPropertyForDeviceParams object
// with the default values initialized.
func NewUpdateCustomPropertyForDeviceParams() *UpdateCustomPropertyForDeviceParams {
	var ()
	return &UpdateCustomPropertyForDeviceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateCustomPropertyForDeviceParamsWithTimeout creates a new UpdateCustomPropertyForDeviceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateCustomPropertyForDeviceParamsWithTimeout(timeout time.Duration) *UpdateCustomPropertyForDeviceParams {
	var ()
	return &UpdateCustomPropertyForDeviceParams{

		timeout: timeout,
	}
}

// NewUpdateCustomPropertyForDeviceParamsWithContext creates a new UpdateCustomPropertyForDeviceParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateCustomPropertyForDeviceParamsWithContext(ctx context.Context) *UpdateCustomPropertyForDeviceParams {
	var ()
	return &UpdateCustomPropertyForDeviceParams{

		Context: ctx,
	}
}

// NewUpdateCustomPropertyForDeviceParamsWithHTTPClient creates a new UpdateCustomPropertyForDeviceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateCustomPropertyForDeviceParamsWithHTTPClient(client *http.Client) *UpdateCustomPropertyForDeviceParams {
	var ()
	return &UpdateCustomPropertyForDeviceParams{
		HTTPClient: client,
	}
}

/*UpdateCustomPropertyForDeviceParams contains all the parameters to send to the API endpoint
for the update custom property for device operation typically these are written to a http.Request
*/
type UpdateCustomPropertyForDeviceParams struct {

	/*DeviceID
	  Unique identifier of a device.

	*/
	DeviceID string
	/*Key
	  Key of the custom property.

	*/
	Key string
	/*Request
	  Specification of the custom property that will be updated.

	*/
	Request UpdateCustomPropertyForDeviceBody
	/*TenantID
	  Unique identifier of a tenant.

	*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update custom property for device params
func (o *UpdateCustomPropertyForDeviceParams) WithTimeout(timeout time.Duration) *UpdateCustomPropertyForDeviceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update custom property for device params
func (o *UpdateCustomPropertyForDeviceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update custom property for device params
func (o *UpdateCustomPropertyForDeviceParams) WithContext(ctx context.Context) *UpdateCustomPropertyForDeviceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update custom property for device params
func (o *UpdateCustomPropertyForDeviceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update custom property for device params
func (o *UpdateCustomPropertyForDeviceParams) WithHTTPClient(client *http.Client) *UpdateCustomPropertyForDeviceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update custom property for device params
func (o *UpdateCustomPropertyForDeviceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceID adds the deviceID to the update custom property for device params
func (o *UpdateCustomPropertyForDeviceParams) WithDeviceID(deviceID string) *UpdateCustomPropertyForDeviceParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the update custom property for device params
func (o *UpdateCustomPropertyForDeviceParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WithKey adds the key to the update custom property for device params
func (o *UpdateCustomPropertyForDeviceParams) WithKey(key string) *UpdateCustomPropertyForDeviceParams {
	o.SetKey(key)
	return o
}

// SetKey adds the key to the update custom property for device params
func (o *UpdateCustomPropertyForDeviceParams) SetKey(key string) {
	o.Key = key
}

// WithRequest adds the request to the update custom property for device params
func (o *UpdateCustomPropertyForDeviceParams) WithRequest(request UpdateCustomPropertyForDeviceBody) *UpdateCustomPropertyForDeviceParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the update custom property for device params
func (o *UpdateCustomPropertyForDeviceParams) SetRequest(request UpdateCustomPropertyForDeviceBody) {
	o.Request = request
}

// WithTenantID adds the tenantID to the update custom property for device params
func (o *UpdateCustomPropertyForDeviceParams) WithTenantID(tenantID string) *UpdateCustomPropertyForDeviceParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the update custom property for device params
func (o *UpdateCustomPropertyForDeviceParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateCustomPropertyForDeviceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param deviceId
	if err := r.SetPathParam("deviceId", o.DeviceID); err != nil {
		return err
	}

	// path param key
	if err := r.SetPathParam("key", o.Key); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.Request); err != nil {
		return err
	}

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
