// Code generated by go-swagger; DO NOT EDIT.

package gateways

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetGatewayBundleUsingGETParams creates a new GetGatewayBundleUsingGETParams object
// with the default values initialized.
func NewGetGatewayBundleUsingGETParams() *GetGatewayBundleUsingGETParams {
	var ()
	return &GetGatewayBundleUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetGatewayBundleUsingGETParamsWithTimeout creates a new GetGatewayBundleUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetGatewayBundleUsingGETParamsWithTimeout(timeout time.Duration) *GetGatewayBundleUsingGETParams {
	var ()
	return &GetGatewayBundleUsingGETParams{

		timeout: timeout,
	}
}

// NewGetGatewayBundleUsingGETParamsWithContext creates a new GetGatewayBundleUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetGatewayBundleUsingGETParamsWithContext(ctx context.Context) *GetGatewayBundleUsingGETParams {
	var ()
	return &GetGatewayBundleUsingGETParams{

		Context: ctx,
	}
}

// NewGetGatewayBundleUsingGETParamsWithHTTPClient creates a new GetGatewayBundleUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetGatewayBundleUsingGETParamsWithHTTPClient(client *http.Client) *GetGatewayBundleUsingGETParams {
	var ()
	return &GetGatewayBundleUsingGETParams{
		HTTPClient: client,
	}
}

/*GetGatewayBundleUsingGETParams contains all the parameters to send to the API endpoint
for the get gateway bundle using g e t operation typically these are written to a http.Request
*/
type GetGatewayBundleUsingGETParams struct {

	/*BundleID
	  Unique identifier of an OSGi bundle

	*/
	BundleID string
	/*GatewayID
	  Unique identifier of a gateway.

	*/
	GatewayID string
	/*TenantID
	  Unique identifier of a tenant.

	*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get gateway bundle using g e t params
func (o *GetGatewayBundleUsingGETParams) WithTimeout(timeout time.Duration) *GetGatewayBundleUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get gateway bundle using g e t params
func (o *GetGatewayBundleUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get gateway bundle using g e t params
func (o *GetGatewayBundleUsingGETParams) WithContext(ctx context.Context) *GetGatewayBundleUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get gateway bundle using g e t params
func (o *GetGatewayBundleUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get gateway bundle using g e t params
func (o *GetGatewayBundleUsingGETParams) WithHTTPClient(client *http.Client) *GetGatewayBundleUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get gateway bundle using g e t params
func (o *GetGatewayBundleUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBundleID adds the bundleID to the get gateway bundle using g e t params
func (o *GetGatewayBundleUsingGETParams) WithBundleID(bundleID string) *GetGatewayBundleUsingGETParams {
	o.SetBundleID(bundleID)
	return o
}

// SetBundleID adds the bundleId to the get gateway bundle using g e t params
func (o *GetGatewayBundleUsingGETParams) SetBundleID(bundleID string) {
	o.BundleID = bundleID
}

// WithGatewayID adds the gatewayID to the get gateway bundle using g e t params
func (o *GetGatewayBundleUsingGETParams) WithGatewayID(gatewayID string) *GetGatewayBundleUsingGETParams {
	o.SetGatewayID(gatewayID)
	return o
}

// SetGatewayID adds the gatewayId to the get gateway bundle using g e t params
func (o *GetGatewayBundleUsingGETParams) SetGatewayID(gatewayID string) {
	o.GatewayID = gatewayID
}

// WithTenantID adds the tenantID to the get gateway bundle using g e t params
func (o *GetGatewayBundleUsingGETParams) WithTenantID(tenantID string) *GetGatewayBundleUsingGETParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the get gateway bundle using g e t params
func (o *GetGatewayBundleUsingGETParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *GetGatewayBundleUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param bundleId
	if err := r.SetPathParam("bundleId", o.BundleID); err != nil {
		return err
	}

	// path param gatewayId
	if err := r.SetPathParam("gatewayId", o.GatewayID); err != nil {
		return err
	}

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
