// Code generated by go-swagger; DO NOT EDIT.

package gateways

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListDeviceRegistrationCertificatesUsingGETParams creates a new ListDeviceRegistrationCertificatesUsingGETParams object
// with the default values initialized.
func NewListDeviceRegistrationCertificatesUsingGETParams() *ListDeviceRegistrationCertificatesUsingGETParams {
	var (
		skipDefault = int32(0)
		topDefault  = int32(100)
	)
	return &ListDeviceRegistrationCertificatesUsingGETParams{
		Skip: &skipDefault,
		Top:  &topDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewListDeviceRegistrationCertificatesUsingGETParamsWithTimeout creates a new ListDeviceRegistrationCertificatesUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListDeviceRegistrationCertificatesUsingGETParamsWithTimeout(timeout time.Duration) *ListDeviceRegistrationCertificatesUsingGETParams {
	var (
		skipDefault = int32(0)
		topDefault  = int32(100)
	)
	return &ListDeviceRegistrationCertificatesUsingGETParams{
		Skip: &skipDefault,
		Top:  &topDefault,

		timeout: timeout,
	}
}

// NewListDeviceRegistrationCertificatesUsingGETParamsWithContext creates a new ListDeviceRegistrationCertificatesUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewListDeviceRegistrationCertificatesUsingGETParamsWithContext(ctx context.Context) *ListDeviceRegistrationCertificatesUsingGETParams {
	var (
		skipDefault = int32(0)
		topDefault  = int32(100)
	)
	return &ListDeviceRegistrationCertificatesUsingGETParams{
		Skip: &skipDefault,
		Top:  &topDefault,

		Context: ctx,
	}
}

// NewListDeviceRegistrationCertificatesUsingGETParamsWithHTTPClient creates a new ListDeviceRegistrationCertificatesUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListDeviceRegistrationCertificatesUsingGETParamsWithHTTPClient(client *http.Client) *ListDeviceRegistrationCertificatesUsingGETParams {
	var (
		skipDefault = int32(0)
		topDefault  = int32(100)
	)
	return &ListDeviceRegistrationCertificatesUsingGETParams{
		Skip:       &skipDefault,
		Top:        &topDefault,
		HTTPClient: client,
	}
}

/*ListDeviceRegistrationCertificatesUsingGETParams contains all the parameters to send to the API endpoint
for the list device registration certificates using g e t operation typically these are written to a http.Request
*/
type ListDeviceRegistrationCertificatesUsingGETParams struct {

	/*GatewayID
	  Unique identifier of a gateway.

	*/
	GatewayID string
	/*Skip
	  This parameter specifies the number of items in the queried collection which will be skipped and therefore not included in the result set.

	*/
	Skip *int32
	/*TenantID
	  Unique identifier of a tenant.

	*/
	TenantID string
	/*Top
	  This parameter restricts the maximum number of items which will be returned by the request.

	*/
	Top *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list device registration certificates using g e t params
func (o *ListDeviceRegistrationCertificatesUsingGETParams) WithTimeout(timeout time.Duration) *ListDeviceRegistrationCertificatesUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list device registration certificates using g e t params
func (o *ListDeviceRegistrationCertificatesUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list device registration certificates using g e t params
func (o *ListDeviceRegistrationCertificatesUsingGETParams) WithContext(ctx context.Context) *ListDeviceRegistrationCertificatesUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list device registration certificates using g e t params
func (o *ListDeviceRegistrationCertificatesUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list device registration certificates using g e t params
func (o *ListDeviceRegistrationCertificatesUsingGETParams) WithHTTPClient(client *http.Client) *ListDeviceRegistrationCertificatesUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list device registration certificates using g e t params
func (o *ListDeviceRegistrationCertificatesUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGatewayID adds the gatewayID to the list device registration certificates using g e t params
func (o *ListDeviceRegistrationCertificatesUsingGETParams) WithGatewayID(gatewayID string) *ListDeviceRegistrationCertificatesUsingGETParams {
	o.SetGatewayID(gatewayID)
	return o
}

// SetGatewayID adds the gatewayId to the list device registration certificates using g e t params
func (o *ListDeviceRegistrationCertificatesUsingGETParams) SetGatewayID(gatewayID string) {
	o.GatewayID = gatewayID
}

// WithSkip adds the skip to the list device registration certificates using g e t params
func (o *ListDeviceRegistrationCertificatesUsingGETParams) WithSkip(skip *int32) *ListDeviceRegistrationCertificatesUsingGETParams {
	o.SetSkip(skip)
	return o
}

// SetSkip adds the skip to the list device registration certificates using g e t params
func (o *ListDeviceRegistrationCertificatesUsingGETParams) SetSkip(skip *int32) {
	o.Skip = skip
}

// WithTenantID adds the tenantID to the list device registration certificates using g e t params
func (o *ListDeviceRegistrationCertificatesUsingGETParams) WithTenantID(tenantID string) *ListDeviceRegistrationCertificatesUsingGETParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the list device registration certificates using g e t params
func (o *ListDeviceRegistrationCertificatesUsingGETParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WithTop adds the top to the list device registration certificates using g e t params
func (o *ListDeviceRegistrationCertificatesUsingGETParams) WithTop(top *int32) *ListDeviceRegistrationCertificatesUsingGETParams {
	o.SetTop(top)
	return o
}

// SetTop adds the top to the list device registration certificates using g e t params
func (o *ListDeviceRegistrationCertificatesUsingGETParams) SetTop(top *int32) {
	o.Top = top
}

// WriteToRequest writes these params to a swagger request
func (o *ListDeviceRegistrationCertificatesUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param gatewayId
	if err := r.SetPathParam("gatewayId", o.GatewayID); err != nil {
		return err
	}

	if o.Skip != nil {

		// query param skip
		var qrSkip int32
		if o.Skip != nil {
			qrSkip = *o.Skip
		}
		qSkip := swag.FormatInt32(qrSkip)
		if qSkip != "" {
			if err := r.SetQueryParam("skip", qSkip); err != nil {
				return err
			}
		}

	}

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if o.Top != nil {

		// query param top
		var qrTop int32
		if o.Top != nil {
			qrTop = *o.Top
		}
		qTop := swag.FormatInt32(qrTop)
		if qTop != "" {
			if err := r.SetQueryParam("top", qTop); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
