// Code generated by go-swagger; DO NOT EDIT.

package gateways

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRevokeGatewayCertificateUsingDELETEParams creates a new RevokeGatewayCertificateUsingDELETEParams object
// with the default values initialized.
func NewRevokeGatewayCertificateUsingDELETEParams() *RevokeGatewayCertificateUsingDELETEParams {
	var ()
	return &RevokeGatewayCertificateUsingDELETEParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRevokeGatewayCertificateUsingDELETEParamsWithTimeout creates a new RevokeGatewayCertificateUsingDELETEParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRevokeGatewayCertificateUsingDELETEParamsWithTimeout(timeout time.Duration) *RevokeGatewayCertificateUsingDELETEParams {
	var ()
	return &RevokeGatewayCertificateUsingDELETEParams{

		timeout: timeout,
	}
}

// NewRevokeGatewayCertificateUsingDELETEParamsWithContext creates a new RevokeGatewayCertificateUsingDELETEParams object
// with the default values initialized, and the ability to set a context for a request
func NewRevokeGatewayCertificateUsingDELETEParamsWithContext(ctx context.Context) *RevokeGatewayCertificateUsingDELETEParams {
	var ()
	return &RevokeGatewayCertificateUsingDELETEParams{

		Context: ctx,
	}
}

// NewRevokeGatewayCertificateUsingDELETEParamsWithHTTPClient creates a new RevokeGatewayCertificateUsingDELETEParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRevokeGatewayCertificateUsingDELETEParamsWithHTTPClient(client *http.Client) *RevokeGatewayCertificateUsingDELETEParams {
	var ()
	return &RevokeGatewayCertificateUsingDELETEParams{
		HTTPClient: client,
	}
}

/*RevokeGatewayCertificateUsingDELETEParams contains all the parameters to send to the API endpoint
for the revoke gateway certificate using d e l e t e operation typically these are written to a http.Request
*/
type RevokeGatewayCertificateUsingDELETEParams struct {

	/*Fingerprint
	  The fingerprint of the certificate hashed with SHA-256 in hex format.

	*/
	Fingerprint string
	/*GatewayID
	  Unique identifier of a gateway.

	*/
	GatewayID string
	/*TenantID
	  Unique identifier of a tenant.

	*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the revoke gateway certificate using d e l e t e params
func (o *RevokeGatewayCertificateUsingDELETEParams) WithTimeout(timeout time.Duration) *RevokeGatewayCertificateUsingDELETEParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the revoke gateway certificate using d e l e t e params
func (o *RevokeGatewayCertificateUsingDELETEParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the revoke gateway certificate using d e l e t e params
func (o *RevokeGatewayCertificateUsingDELETEParams) WithContext(ctx context.Context) *RevokeGatewayCertificateUsingDELETEParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the revoke gateway certificate using d e l e t e params
func (o *RevokeGatewayCertificateUsingDELETEParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the revoke gateway certificate using d e l e t e params
func (o *RevokeGatewayCertificateUsingDELETEParams) WithHTTPClient(client *http.Client) *RevokeGatewayCertificateUsingDELETEParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the revoke gateway certificate using d e l e t e params
func (o *RevokeGatewayCertificateUsingDELETEParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFingerprint adds the fingerprint to the revoke gateway certificate using d e l e t e params
func (o *RevokeGatewayCertificateUsingDELETEParams) WithFingerprint(fingerprint string) *RevokeGatewayCertificateUsingDELETEParams {
	o.SetFingerprint(fingerprint)
	return o
}

// SetFingerprint adds the fingerprint to the revoke gateway certificate using d e l e t e params
func (o *RevokeGatewayCertificateUsingDELETEParams) SetFingerprint(fingerprint string) {
	o.Fingerprint = fingerprint
}

// WithGatewayID adds the gatewayID to the revoke gateway certificate using d e l e t e params
func (o *RevokeGatewayCertificateUsingDELETEParams) WithGatewayID(gatewayID string) *RevokeGatewayCertificateUsingDELETEParams {
	o.SetGatewayID(gatewayID)
	return o
}

// SetGatewayID adds the gatewayId to the revoke gateway certificate using d e l e t e params
func (o *RevokeGatewayCertificateUsingDELETEParams) SetGatewayID(gatewayID string) {
	o.GatewayID = gatewayID
}

// WithTenantID adds the tenantID to the revoke gateway certificate using d e l e t e params
func (o *RevokeGatewayCertificateUsingDELETEParams) WithTenantID(tenantID string) *RevokeGatewayCertificateUsingDELETEParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the revoke gateway certificate using d e l e t e params
func (o *RevokeGatewayCertificateUsingDELETEParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *RevokeGatewayCertificateUsingDELETEParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param fingerprint
	if err := r.SetPathParam("fingerprint", o.Fingerprint); err != nil {
		return err
	}

	// path param gatewayId
	if err := r.SetPathParam("gatewayId", o.GatewayID); err != nil {
		return err
	}

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
