// Code generated by go-swagger; DO NOT EDIT.

package gateways

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateGatewayConfigurationUsingPUTParams creates a new UpdateGatewayConfigurationUsingPUTParams object
// with the default values initialized.
func NewUpdateGatewayConfigurationUsingPUTParams() *UpdateGatewayConfigurationUsingPUTParams {
	var ()
	return &UpdateGatewayConfigurationUsingPUTParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateGatewayConfigurationUsingPUTParamsWithTimeout creates a new UpdateGatewayConfigurationUsingPUTParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateGatewayConfigurationUsingPUTParamsWithTimeout(timeout time.Duration) *UpdateGatewayConfigurationUsingPUTParams {
	var ()
	return &UpdateGatewayConfigurationUsingPUTParams{

		timeout: timeout,
	}
}

// NewUpdateGatewayConfigurationUsingPUTParamsWithContext creates a new UpdateGatewayConfigurationUsingPUTParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateGatewayConfigurationUsingPUTParamsWithContext(ctx context.Context) *UpdateGatewayConfigurationUsingPUTParams {
	var ()
	return &UpdateGatewayConfigurationUsingPUTParams{

		Context: ctx,
	}
}

// NewUpdateGatewayConfigurationUsingPUTParamsWithHTTPClient creates a new UpdateGatewayConfigurationUsingPUTParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateGatewayConfigurationUsingPUTParamsWithHTTPClient(client *http.Client) *UpdateGatewayConfigurationUsingPUTParams {
	var ()
	return &UpdateGatewayConfigurationUsingPUTParams{
		HTTPClient: client,
	}
}

/*UpdateGatewayConfigurationUsingPUTParams contains all the parameters to send to the API endpoint
for the update gateway configuration using p u t operation typically these are written to a http.Request
*/
type UpdateGatewayConfigurationUsingPUTParams struct {

	/*GatewayID
	  Unique identifier of a gateway.

	*/
	GatewayID string
	/*Request
	  Gateway configuration file.

	*/
	Request string
	/*TenantID
	  Unique identifier of a tenant.

	*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update gateway configuration using p u t params
func (o *UpdateGatewayConfigurationUsingPUTParams) WithTimeout(timeout time.Duration) *UpdateGatewayConfigurationUsingPUTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update gateway configuration using p u t params
func (o *UpdateGatewayConfigurationUsingPUTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update gateway configuration using p u t params
func (o *UpdateGatewayConfigurationUsingPUTParams) WithContext(ctx context.Context) *UpdateGatewayConfigurationUsingPUTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update gateway configuration using p u t params
func (o *UpdateGatewayConfigurationUsingPUTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update gateway configuration using p u t params
func (o *UpdateGatewayConfigurationUsingPUTParams) WithHTTPClient(client *http.Client) *UpdateGatewayConfigurationUsingPUTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update gateway configuration using p u t params
func (o *UpdateGatewayConfigurationUsingPUTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGatewayID adds the gatewayID to the update gateway configuration using p u t params
func (o *UpdateGatewayConfigurationUsingPUTParams) WithGatewayID(gatewayID string) *UpdateGatewayConfigurationUsingPUTParams {
	o.SetGatewayID(gatewayID)
	return o
}

// SetGatewayID adds the gatewayId to the update gateway configuration using p u t params
func (o *UpdateGatewayConfigurationUsingPUTParams) SetGatewayID(gatewayID string) {
	o.GatewayID = gatewayID
}

// WithRequest adds the request to the update gateway configuration using p u t params
func (o *UpdateGatewayConfigurationUsingPUTParams) WithRequest(request string) *UpdateGatewayConfigurationUsingPUTParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the update gateway configuration using p u t params
func (o *UpdateGatewayConfigurationUsingPUTParams) SetRequest(request string) {
	o.Request = request
}

// WithTenantID adds the tenantID to the update gateway configuration using p u t params
func (o *UpdateGatewayConfigurationUsingPUTParams) WithTenantID(tenantID string) *UpdateGatewayConfigurationUsingPUTParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the update gateway configuration using p u t params
func (o *UpdateGatewayConfigurationUsingPUTParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateGatewayConfigurationUsingPUTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param gatewayId
	if err := r.SetPathParam("gatewayId", o.GatewayID); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.Request); err != nil {
		return err
	}

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
