// Code generated by go-swagger; DO NOT EDIT.

package sensors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateCustomPropertyForSensorParams creates a new CreateCustomPropertyForSensorParams object
// with the default values initialized.
func NewCreateCustomPropertyForSensorParams() *CreateCustomPropertyForSensorParams {
	var ()
	return &CreateCustomPropertyForSensorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateCustomPropertyForSensorParamsWithTimeout creates a new CreateCustomPropertyForSensorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateCustomPropertyForSensorParamsWithTimeout(timeout time.Duration) *CreateCustomPropertyForSensorParams {
	var ()
	return &CreateCustomPropertyForSensorParams{

		timeout: timeout,
	}
}

// NewCreateCustomPropertyForSensorParamsWithContext creates a new CreateCustomPropertyForSensorParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateCustomPropertyForSensorParamsWithContext(ctx context.Context) *CreateCustomPropertyForSensorParams {
	var ()
	return &CreateCustomPropertyForSensorParams{

		Context: ctx,
	}
}

// NewCreateCustomPropertyForSensorParamsWithHTTPClient creates a new CreateCustomPropertyForSensorParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateCustomPropertyForSensorParamsWithHTTPClient(client *http.Client) *CreateCustomPropertyForSensorParams {
	var ()
	return &CreateCustomPropertyForSensorParams{
		HTTPClient: client,
	}
}

/*CreateCustomPropertyForSensorParams contains all the parameters to send to the API endpoint
for the create custom property for sensor operation typically these are written to a http.Request
*/
type CreateCustomPropertyForSensorParams struct {

	/*Request
	  Specification of the custom property that will be created.

	*/
	Request CreateCustomPropertyForSensorBody
	/*SensorID
	  Unique identifier of a sensor.

	*/
	SensorID string
	/*TenantID
	  Unique identifier of a tenant.

	*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create custom property for sensor params
func (o *CreateCustomPropertyForSensorParams) WithTimeout(timeout time.Duration) *CreateCustomPropertyForSensorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create custom property for sensor params
func (o *CreateCustomPropertyForSensorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create custom property for sensor params
func (o *CreateCustomPropertyForSensorParams) WithContext(ctx context.Context) *CreateCustomPropertyForSensorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create custom property for sensor params
func (o *CreateCustomPropertyForSensorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create custom property for sensor params
func (o *CreateCustomPropertyForSensorParams) WithHTTPClient(client *http.Client) *CreateCustomPropertyForSensorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create custom property for sensor params
func (o *CreateCustomPropertyForSensorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the create custom property for sensor params
func (o *CreateCustomPropertyForSensorParams) WithRequest(request CreateCustomPropertyForSensorBody) *CreateCustomPropertyForSensorParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the create custom property for sensor params
func (o *CreateCustomPropertyForSensorParams) SetRequest(request CreateCustomPropertyForSensorBody) {
	o.Request = request
}

// WithSensorID adds the sensorID to the create custom property for sensor params
func (o *CreateCustomPropertyForSensorParams) WithSensorID(sensorID string) *CreateCustomPropertyForSensorParams {
	o.SetSensorID(sensorID)
	return o
}

// SetSensorID adds the sensorId to the create custom property for sensor params
func (o *CreateCustomPropertyForSensorParams) SetSensorID(sensorID string) {
	o.SensorID = sensorID
}

// WithTenantID adds the tenantID to the create custom property for sensor params
func (o *CreateCustomPropertyForSensorParams) WithTenantID(tenantID string) *CreateCustomPropertyForSensorParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the create custom property for sensor params
func (o *CreateCustomPropertyForSensorParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateCustomPropertyForSensorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Request); err != nil {
		return err
	}

	// path param sensorId
	if err := r.SetPathParam("sensorId", o.SensorID); err != nil {
		return err
	}

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
