// Code generated by go-swagger; DO NOT EDIT.

package sensors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSensorCountUsingGETParams creates a new GetSensorCountUsingGETParams object
// with the default values initialized.
func NewGetSensorCountUsingGETParams() *GetSensorCountUsingGETParams {
	var ()
	return &GetSensorCountUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSensorCountUsingGETParamsWithTimeout creates a new GetSensorCountUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSensorCountUsingGETParamsWithTimeout(timeout time.Duration) *GetSensorCountUsingGETParams {
	var ()
	return &GetSensorCountUsingGETParams{

		timeout: timeout,
	}
}

// NewGetSensorCountUsingGETParamsWithContext creates a new GetSensorCountUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSensorCountUsingGETParamsWithContext(ctx context.Context) *GetSensorCountUsingGETParams {
	var ()
	return &GetSensorCountUsingGETParams{

		Context: ctx,
	}
}

// NewGetSensorCountUsingGETParamsWithHTTPClient creates a new GetSensorCountUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSensorCountUsingGETParamsWithHTTPClient(client *http.Client) *GetSensorCountUsingGETParams {
	var ()
	return &GetSensorCountUsingGETParams{
		HTTPClient: client,
	}
}

/*GetSensorCountUsingGETParams contains all the parameters to send to the API endpoint
for the get sensor count using g e t operation typically these are written to a http.Request
*/
type GetSensorCountUsingGETParams struct {

	/*TenantID
	  Unique identifier of a tenant.

	*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get sensor count using g e t params
func (o *GetSensorCountUsingGETParams) WithTimeout(timeout time.Duration) *GetSensorCountUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get sensor count using g e t params
func (o *GetSensorCountUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get sensor count using g e t params
func (o *GetSensorCountUsingGETParams) WithContext(ctx context.Context) *GetSensorCountUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get sensor count using g e t params
func (o *GetSensorCountUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get sensor count using g e t params
func (o *GetSensorCountUsingGETParams) WithHTTPClient(client *http.Client) *GetSensorCountUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get sensor count using g e t params
func (o *GetSensorCountUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTenantID adds the tenantID to the get sensor count using g e t params
func (o *GetSensorCountUsingGETParams) WithTenantID(tenantID string) *GetSensorCountUsingGETParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the get sensor count using g e t params
func (o *GetSensorCountUsingGETParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *GetSensorCountUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
