// Code generated by go-swagger; DO NOT EDIT.

package vendors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateVendorUsingPOSTReader is a Reader for the CreateVendorUsingPOST structure.
type CreateVendorUsingPOSTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateVendorUsingPOSTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateVendorUsingPOSTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateVendorUsingPOSTOK creates a CreateVendorUsingPOSTOK with default headers values
func NewCreateVendorUsingPOSTOK() *CreateVendorUsingPOSTOK {
	return &CreateVendorUsingPOSTOK{}
}

/*CreateVendorUsingPOSTOK handles this case with default header values.

OK
*/
type CreateVendorUsingPOSTOK struct {
	Payload *CreateVendorUsingPOSTOKBody
}

func (o *CreateVendorUsingPOSTOK) Error() string {
	return fmt.Sprintf("[POST /v1/vendors][%d] createVendorUsingPOSTOK  %+v", 200, o.Payload)
}

func (o *CreateVendorUsingPOSTOK) GetPayload() *CreateVendorUsingPOSTOKBody {
	return o.Payload
}

func (o *CreateVendorUsingPOSTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreateVendorUsingPOSTOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*CreateVendorUsingPOSTBody VendorBean
swagger:model CreateVendorUsingPOSTBody
*/
type CreateVendorUsingPOSTBody struct {

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this create vendor using p o s t body
func (o *CreateVendorUsingPOSTBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreateVendorUsingPOSTBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateVendorUsingPOSTBody) UnmarshalBinary(b []byte) error {
	var res CreateVendorUsingPOSTBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*CreateVendorUsingPOSTOKBody VendorBean
swagger:model CreateVendorUsingPOSTOKBody
*/
type CreateVendorUsingPOSTOKBody struct {

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this create vendor using p o s t o k body
func (o *CreateVendorUsingPOSTOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreateVendorUsingPOSTOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateVendorUsingPOSTOKBody) UnmarshalBinary(b []byte) error {
	var res CreateVendorUsingPOSTOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
