// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateCustomPropertyForUserReader is a Reader for the CreateCustomPropertyForUser structure.
type CreateCustomPropertyForUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateCustomPropertyForUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateCustomPropertyForUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateCustomPropertyForUserBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateCustomPropertyForUserNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewCreateCustomPropertyForUserConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateCustomPropertyForUserOK creates a CreateCustomPropertyForUserOK with default headers values
func NewCreateCustomPropertyForUserOK() *CreateCustomPropertyForUserOK {
	return &CreateCustomPropertyForUserOK{}
}

/*CreateCustomPropertyForUserOK handles this case with default header values.

Successfully created custom property.
*/
type CreateCustomPropertyForUserOK struct {
	Payload *CreateCustomPropertyForUserOKBody
}

func (o *CreateCustomPropertyForUserOK) Error() string {
	return fmt.Sprintf("[POST /v1/users/{userId}/customProperties][%d] createCustomPropertyForUserOK  %+v", 200, o.Payload)
}

func (o *CreateCustomPropertyForUserOK) GetPayload() *CreateCustomPropertyForUserOKBody {
	return o.Payload
}

func (o *CreateCustomPropertyForUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreateCustomPropertyForUserOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCustomPropertyForUserBadRequest creates a CreateCustomPropertyForUserBadRequest with default headers values
func NewCreateCustomPropertyForUserBadRequest() *CreateCustomPropertyForUserBadRequest {
	return &CreateCustomPropertyForUserBadRequest{}
}

/*CreateCustomPropertyForUserBadRequest handles this case with default header values.

HTTP request is malformed.
*/
type CreateCustomPropertyForUserBadRequest struct {
	Payload *CreateCustomPropertyForUserBadRequestBody
}

func (o *CreateCustomPropertyForUserBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/users/{userId}/customProperties][%d] createCustomPropertyForUserBadRequest  %+v", 400, o.Payload)
}

func (o *CreateCustomPropertyForUserBadRequest) GetPayload() *CreateCustomPropertyForUserBadRequestBody {
	return o.Payload
}

func (o *CreateCustomPropertyForUserBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreateCustomPropertyForUserBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCustomPropertyForUserNotFound creates a CreateCustomPropertyForUserNotFound with default headers values
func NewCreateCustomPropertyForUserNotFound() *CreateCustomPropertyForUserNotFound {
	return &CreateCustomPropertyForUserNotFound{}
}

/*CreateCustomPropertyForUserNotFound handles this case with default header values.

User with specified id does not exist.
*/
type CreateCustomPropertyForUserNotFound struct {
	Payload *CreateCustomPropertyForUserNotFoundBody
}

func (o *CreateCustomPropertyForUserNotFound) Error() string {
	return fmt.Sprintf("[POST /v1/users/{userId}/customProperties][%d] createCustomPropertyForUserNotFound  %+v", 404, o.Payload)
}

func (o *CreateCustomPropertyForUserNotFound) GetPayload() *CreateCustomPropertyForUserNotFoundBody {
	return o.Payload
}

func (o *CreateCustomPropertyForUserNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreateCustomPropertyForUserNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCustomPropertyForUserConflict creates a CreateCustomPropertyForUserConflict with default headers values
func NewCreateCustomPropertyForUserConflict() *CreateCustomPropertyForUserConflict {
	return &CreateCustomPropertyForUserConflict{}
}

/*CreateCustomPropertyForUserConflict handles this case with default header values.

Custom property with specified key already exists.
*/
type CreateCustomPropertyForUserConflict struct {
	Payload *CreateCustomPropertyForUserConflictBody
}

func (o *CreateCustomPropertyForUserConflict) Error() string {
	return fmt.Sprintf("[POST /v1/users/{userId}/customProperties][%d] createCustomPropertyForUserConflict  %+v", 409, o.Payload)
}

func (o *CreateCustomPropertyForUserConflict) GetPayload() *CreateCustomPropertyForUserConflictBody {
	return o.Payload
}

func (o *CreateCustomPropertyForUserConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreateCustomPropertyForUserConflictBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*CreateCustomPropertyForUserBadRequestBody Response
swagger:model CreateCustomPropertyForUserBadRequestBody
*/
type CreateCustomPropertyForUserBadRequestBody struct {

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this create custom property for user bad request body
func (o *CreateCustomPropertyForUserBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateCustomPropertyForUserBadRequestBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("createCustomPropertyForUserBadRequest"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateCustomPropertyForUserBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateCustomPropertyForUserBadRequestBody) UnmarshalBinary(b []byte) error {
	var res CreateCustomPropertyForUserBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*CreateCustomPropertyForUserBody CustomPropertyBean
swagger:model CreateCustomPropertyForUserBody
*/
type CreateCustomPropertyForUserBody struct {

	// A unique identifier of a custom property. Is defined by the user. This field is an immutable.
	// Required: true
	Key *string `json:"key"`

	// Value of the custom property.
	// Required: true
	Value *string `json:"value"`
}

// Validate validates this create custom property for user body
func (o *CreateCustomPropertyForUserBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateKey(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateCustomPropertyForUserBody) validateKey(formats strfmt.Registry) error {

	if err := validate.Required("request"+"."+"key", "body", o.Key); err != nil {
		return err
	}

	return nil
}

func (o *CreateCustomPropertyForUserBody) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("request"+"."+"value", "body", o.Value); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateCustomPropertyForUserBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateCustomPropertyForUserBody) UnmarshalBinary(b []byte) error {
	var res CreateCustomPropertyForUserBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*CreateCustomPropertyForUserConflictBody Response
swagger:model CreateCustomPropertyForUserConflictBody
*/
type CreateCustomPropertyForUserConflictBody struct {

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this create custom property for user conflict body
func (o *CreateCustomPropertyForUserConflictBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateCustomPropertyForUserConflictBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("createCustomPropertyForUserConflict"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateCustomPropertyForUserConflictBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateCustomPropertyForUserConflictBody) UnmarshalBinary(b []byte) error {
	var res CreateCustomPropertyForUserConflictBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*CreateCustomPropertyForUserNotFoundBody Response
swagger:model CreateCustomPropertyForUserNotFoundBody
*/
type CreateCustomPropertyForUserNotFoundBody struct {

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this create custom property for user not found body
func (o *CreateCustomPropertyForUserNotFoundBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateCustomPropertyForUserNotFoundBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("createCustomPropertyForUserNotFound"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateCustomPropertyForUserNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateCustomPropertyForUserNotFoundBody) UnmarshalBinary(b []byte) error {
	var res CreateCustomPropertyForUserNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*CreateCustomPropertyForUserOKBody CustomPropertyBean
swagger:model CreateCustomPropertyForUserOKBody
*/
type CreateCustomPropertyForUserOKBody struct {

	// A unique identifier of a custom property. Is defined by the user. This field is an immutable.
	// Required: true
	Key *string `json:"key"`

	// Value of the custom property.
	// Required: true
	Value *string `json:"value"`
}

// Validate validates this create custom property for user o k body
func (o *CreateCustomPropertyForUserOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateKey(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateCustomPropertyForUserOKBody) validateKey(formats strfmt.Registry) error {

	if err := validate.Required("createCustomPropertyForUserOK"+"."+"key", "body", o.Key); err != nil {
		return err
	}

	return nil
}

func (o *CreateCustomPropertyForUserOKBody) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("createCustomPropertyForUserOK"+"."+"value", "body", o.Value); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateCustomPropertyForUserOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateCustomPropertyForUserOKBody) UnmarshalBinary(b []byte) error {
	var res CreateCustomPropertyForUserOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
