// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetUserTenantAssignmentsUsingGET1Params creates a new GetUserTenantAssignmentsUsingGET1Params object
// with the default values initialized.
func NewGetUserTenantAssignmentsUsingGET1Params() *GetUserTenantAssignmentsUsingGET1Params {
	var (
		skipDefault = int32(0)
		topDefault  = int32(100)
	)
	return &GetUserTenantAssignmentsUsingGET1Params{
		Skip: &skipDefault,
		Top:  &topDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUserTenantAssignmentsUsingGET1ParamsWithTimeout creates a new GetUserTenantAssignmentsUsingGET1Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUserTenantAssignmentsUsingGET1ParamsWithTimeout(timeout time.Duration) *GetUserTenantAssignmentsUsingGET1Params {
	var (
		skipDefault = int32(0)
		topDefault  = int32(100)
	)
	return &GetUserTenantAssignmentsUsingGET1Params{
		Skip: &skipDefault,
		Top:  &topDefault,

		timeout: timeout,
	}
}

// NewGetUserTenantAssignmentsUsingGET1ParamsWithContext creates a new GetUserTenantAssignmentsUsingGET1Params object
// with the default values initialized, and the ability to set a context for a request
func NewGetUserTenantAssignmentsUsingGET1ParamsWithContext(ctx context.Context) *GetUserTenantAssignmentsUsingGET1Params {
	var (
		skipDefault = int32(0)
		topDefault  = int32(100)
	)
	return &GetUserTenantAssignmentsUsingGET1Params{
		Skip: &skipDefault,
		Top:  &topDefault,

		Context: ctx,
	}
}

// NewGetUserTenantAssignmentsUsingGET1ParamsWithHTTPClient creates a new GetUserTenantAssignmentsUsingGET1Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetUserTenantAssignmentsUsingGET1ParamsWithHTTPClient(client *http.Client) *GetUserTenantAssignmentsUsingGET1Params {
	var (
		skipDefault = int32(0)
		topDefault  = int32(100)
	)
	return &GetUserTenantAssignmentsUsingGET1Params{
		Skip:       &skipDefault,
		Top:        &topDefault,
		HTTPClient: client,
	}
}

/*GetUserTenantAssignmentsUsingGET1Params contains all the parameters to send to the API endpoint
for the get user tenant assignments using g e t 1 operation typically these are written to a http.Request
*/
type GetUserTenantAssignmentsUsingGET1Params struct {

	/*Filter
	  This parameter allows clients to filter the collection of attributes of an entity. For example, an entity with a specific name can be requested using the following syntax filter=name eq 'entityname'. Multiple filters are supported and should be combined with 'and' or 'or' operators.

	*/
	Filter *string
	/*Orderby
	  This parameter allows clients to order the collection by specific attributes both in ascending and descending order. For example 'orderby=id desc'.

	*/
	Orderby *string
	/*Skip
	  This parameter specifies the number of items in the queried collection which will be skipped and therefore not included in the result set.

	*/
	Skip *int32
	/*Top
	  This parameter restricts the maximum number of items which will be returned by the request.

	*/
	Top *int32
	/*UserID
	  Unique identifier of a user.

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get user tenant assignments using g e t 1 params
func (o *GetUserTenantAssignmentsUsingGET1Params) WithTimeout(timeout time.Duration) *GetUserTenantAssignmentsUsingGET1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get user tenant assignments using g e t 1 params
func (o *GetUserTenantAssignmentsUsingGET1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get user tenant assignments using g e t 1 params
func (o *GetUserTenantAssignmentsUsingGET1Params) WithContext(ctx context.Context) *GetUserTenantAssignmentsUsingGET1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get user tenant assignments using g e t 1 params
func (o *GetUserTenantAssignmentsUsingGET1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get user tenant assignments using g e t 1 params
func (o *GetUserTenantAssignmentsUsingGET1Params) WithHTTPClient(client *http.Client) *GetUserTenantAssignmentsUsingGET1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get user tenant assignments using g e t 1 params
func (o *GetUserTenantAssignmentsUsingGET1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilter adds the filter to the get user tenant assignments using g e t 1 params
func (o *GetUserTenantAssignmentsUsingGET1Params) WithFilter(filter *string) *GetUserTenantAssignmentsUsingGET1Params {
	o.SetFilter(filter)
	return o
}

// SetFilter adds the filter to the get user tenant assignments using g e t 1 params
func (o *GetUserTenantAssignmentsUsingGET1Params) SetFilter(filter *string) {
	o.Filter = filter
}

// WithOrderby adds the orderby to the get user tenant assignments using g e t 1 params
func (o *GetUserTenantAssignmentsUsingGET1Params) WithOrderby(orderby *string) *GetUserTenantAssignmentsUsingGET1Params {
	o.SetOrderby(orderby)
	return o
}

// SetOrderby adds the orderby to the get user tenant assignments using g e t 1 params
func (o *GetUserTenantAssignmentsUsingGET1Params) SetOrderby(orderby *string) {
	o.Orderby = orderby
}

// WithSkip adds the skip to the get user tenant assignments using g e t 1 params
func (o *GetUserTenantAssignmentsUsingGET1Params) WithSkip(skip *int32) *GetUserTenantAssignmentsUsingGET1Params {
	o.SetSkip(skip)
	return o
}

// SetSkip adds the skip to the get user tenant assignments using g e t 1 params
func (o *GetUserTenantAssignmentsUsingGET1Params) SetSkip(skip *int32) {
	o.Skip = skip
}

// WithTop adds the top to the get user tenant assignments using g e t 1 params
func (o *GetUserTenantAssignmentsUsingGET1Params) WithTop(top *int32) *GetUserTenantAssignmentsUsingGET1Params {
	o.SetTop(top)
	return o
}

// SetTop adds the top to the get user tenant assignments using g e t 1 params
func (o *GetUserTenantAssignmentsUsingGET1Params) SetTop(top *int32) {
	o.Top = top
}

// WithUserID adds the userID to the get user tenant assignments using g e t 1 params
func (o *GetUserTenantAssignmentsUsingGET1Params) WithUserID(userID string) *GetUserTenantAssignmentsUsingGET1Params {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get user tenant assignments using g e t 1 params
func (o *GetUserTenantAssignmentsUsingGET1Params) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserTenantAssignmentsUsingGET1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Filter != nil {

		// query param filter
		var qrFilter string
		if o.Filter != nil {
			qrFilter = *o.Filter
		}
		qFilter := qrFilter
		if qFilter != "" {
			if err := r.SetQueryParam("filter", qFilter); err != nil {
				return err
			}
		}

	}

	if o.Orderby != nil {

		// query param orderby
		var qrOrderby string
		if o.Orderby != nil {
			qrOrderby = *o.Orderby
		}
		qOrderby := qrOrderby
		if qOrderby != "" {
			if err := r.SetQueryParam("orderby", qOrderby); err != nil {
				return err
			}
		}

	}

	if o.Skip != nil {

		// query param skip
		var qrSkip int32
		if o.Skip != nil {
			qrSkip = *o.Skip
		}
		qSkip := swag.FormatInt32(qrSkip)
		if qSkip != "" {
			if err := r.SetQueryParam("skip", qSkip); err != nil {
				return err
			}
		}

	}

	if o.Top != nil {

		// query param top
		var qrTop int32
		if o.Top != nil {
			qrTop = *o.Top
		}
		qTop := swag.FormatInt32(qrTop)
		if qTop != "" {
			if err := r.SetQueryParam("top", qTop); err != nil {
				return err
			}
		}

	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
