// Code generated by go-swagger; DO NOT EDIT.

package tenants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateTenantUsingPOSTReader is a Reader for the CreateTenantUsingPOST structure.
type CreateTenantUsingPOSTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateTenantUsingPOSTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateTenantUsingPOSTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateTenantUsingPOSTBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewCreateTenantUsingPOSTConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateTenantUsingPOSTOK creates a CreateTenantUsingPOSTOK with default headers values
func NewCreateTenantUsingPOSTOK() *CreateTenantUsingPOSTOK {
	return &CreateTenantUsingPOSTOK{}
}

/*CreateTenantUsingPOSTOK handles this case with default header values.

Successfully created tenant.
*/
type CreateTenantUsingPOSTOK struct {
	Payload *CreateTenantUsingPOSTOKBody
}

func (o *CreateTenantUsingPOSTOK) Error() string {
	return fmt.Sprintf("[POST /v1/tenants][%d] createTenantUsingPOSTOK  %+v", 200, o.Payload)
}

func (o *CreateTenantUsingPOSTOK) GetPayload() *CreateTenantUsingPOSTOKBody {
	return o.Payload
}

func (o *CreateTenantUsingPOSTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreateTenantUsingPOSTOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateTenantUsingPOSTBadRequest creates a CreateTenantUsingPOSTBadRequest with default headers values
func NewCreateTenantUsingPOSTBadRequest() *CreateTenantUsingPOSTBadRequest {
	return &CreateTenantUsingPOSTBadRequest{}
}

/*CreateTenantUsingPOSTBadRequest handles this case with default header values.

HTTP request is malformed.
*/
type CreateTenantUsingPOSTBadRequest struct {
	Payload *CreateTenantUsingPOSTBadRequestBody
}

func (o *CreateTenantUsingPOSTBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/tenants][%d] createTenantUsingPOSTBadRequest  %+v", 400, o.Payload)
}

func (o *CreateTenantUsingPOSTBadRequest) GetPayload() *CreateTenantUsingPOSTBadRequestBody {
	return o.Payload
}

func (o *CreateTenantUsingPOSTBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreateTenantUsingPOSTBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateTenantUsingPOSTConflict creates a CreateTenantUsingPOSTConflict with default headers values
func NewCreateTenantUsingPOSTConflict() *CreateTenantUsingPOSTConflict {
	return &CreateTenantUsingPOSTConflict{}
}

/*CreateTenantUsingPOSTConflict handles this case with default header values.

Tenant name already exists.
*/
type CreateTenantUsingPOSTConflict struct {
	Payload *CreateTenantUsingPOSTConflictBody
}

func (o *CreateTenantUsingPOSTConflict) Error() string {
	return fmt.Sprintf("[POST /v1/tenants][%d] createTenantUsingPOSTConflict  %+v", 409, o.Payload)
}

func (o *CreateTenantUsingPOSTConflict) GetPayload() *CreateTenantUsingPOSTConflictBody {
	return o.Payload
}

func (o *CreateTenantUsingPOSTConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreateTenantUsingPOSTConflictBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*CreateTenantUsingPOSTBadRequestBody Response
swagger:model CreateTenantUsingPOSTBadRequestBody
*/
type CreateTenantUsingPOSTBadRequestBody struct {

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this create tenant using p o s t bad request body
func (o *CreateTenantUsingPOSTBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateTenantUsingPOSTBadRequestBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("createTenantUsingPOSTBadRequest"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateTenantUsingPOSTBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateTenantUsingPOSTBadRequestBody) UnmarshalBinary(b []byte) error {
	var res CreateTenantUsingPOSTBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*CreateTenantUsingPOSTBody TenantBean
swagger:model CreateTenantUsingPOSTBody
*/
type CreateTenantUsingPOSTBody struct {

	// A set of user defined properties represented as key value pair.
	CustomProperties []*CreateTenantUsingPOSTParamsBodyCustomPropertiesItems0 `json:"customProperties"`

	// The unique identifier of the tenant generated by the system and unique across platform tenant. This field is immutable.
	// Read Only: true
	ID string `json:"id,omitempty"`

	// The name of the tenant.
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this create tenant using p o s t body
func (o *CreateTenantUsingPOSTBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCustomProperties(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateTenantUsingPOSTBody) validateCustomProperties(formats strfmt.Registry) error {

	if swag.IsZero(o.CustomProperties) { // not required
		return nil
	}

	for i := 0; i < len(o.CustomProperties); i++ {
		if swag.IsZero(o.CustomProperties[i]) { // not required
			continue
		}

		if o.CustomProperties[i] != nil {
			if err := o.CustomProperties[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("request" + "." + "customProperties" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *CreateTenantUsingPOSTBody) validateName(formats strfmt.Registry) error {

	if err := validate.Required("request"+"."+"name", "body", o.Name); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateTenantUsingPOSTBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateTenantUsingPOSTBody) UnmarshalBinary(b []byte) error {
	var res CreateTenantUsingPOSTBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*CreateTenantUsingPOSTConflictBody Response
swagger:model CreateTenantUsingPOSTConflictBody
*/
type CreateTenantUsingPOSTConflictBody struct {

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this create tenant using p o s t conflict body
func (o *CreateTenantUsingPOSTConflictBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateTenantUsingPOSTConflictBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("createTenantUsingPOSTConflict"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateTenantUsingPOSTConflictBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateTenantUsingPOSTConflictBody) UnmarshalBinary(b []byte) error {
	var res CreateTenantUsingPOSTConflictBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*CreateTenantUsingPOSTOKBody TenantBean
swagger:model CreateTenantUsingPOSTOKBody
*/
type CreateTenantUsingPOSTOKBody struct {

	// A set of user defined properties represented as key value pair.
	CustomProperties []*CreateTenantUsingPOSTOKBodyCustomPropertiesItems0 `json:"customProperties"`

	// The unique identifier of the tenant generated by the system and unique across platform tenant. This field is immutable.
	// Read Only: true
	ID string `json:"id,omitempty"`

	// The name of the tenant.
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this create tenant using p o s t o k body
func (o *CreateTenantUsingPOSTOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCustomProperties(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateTenantUsingPOSTOKBody) validateCustomProperties(formats strfmt.Registry) error {

	if swag.IsZero(o.CustomProperties) { // not required
		return nil
	}

	for i := 0; i < len(o.CustomProperties); i++ {
		if swag.IsZero(o.CustomProperties[i]) { // not required
			continue
		}

		if o.CustomProperties[i] != nil {
			if err := o.CustomProperties[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("createTenantUsingPOSTOK" + "." + "customProperties" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *CreateTenantUsingPOSTOKBody) validateName(formats strfmt.Registry) error {

	if err := validate.Required("createTenantUsingPOSTOK"+"."+"name", "body", o.Name); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateTenantUsingPOSTOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateTenantUsingPOSTOKBody) UnmarshalBinary(b []byte) error {
	var res CreateTenantUsingPOSTOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*CreateTenantUsingPOSTOKBodyCustomPropertiesItems0 CustomPropertyBean
swagger:model CreateTenantUsingPOSTOKBodyCustomPropertiesItems0
*/
type CreateTenantUsingPOSTOKBodyCustomPropertiesItems0 struct {

	// A unique identifier of a custom property. Is defined by the user. This field is an immutable.
	// Required: true
	Key *string `json:"key"`

	// Value of the custom property.
	// Required: true
	Value *string `json:"value"`
}

// Validate validates this create tenant using p o s t o k body custom properties items0
func (o *CreateTenantUsingPOSTOKBodyCustomPropertiesItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateKey(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateTenantUsingPOSTOKBodyCustomPropertiesItems0) validateKey(formats strfmt.Registry) error {

	if err := validate.Required("key", "body", o.Key); err != nil {
		return err
	}

	return nil
}

func (o *CreateTenantUsingPOSTOKBodyCustomPropertiesItems0) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", o.Value); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateTenantUsingPOSTOKBodyCustomPropertiesItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateTenantUsingPOSTOKBodyCustomPropertiesItems0) UnmarshalBinary(b []byte) error {
	var res CreateTenantUsingPOSTOKBodyCustomPropertiesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*CreateTenantUsingPOSTParamsBodyCustomPropertiesItems0 CustomPropertyBean
swagger:model CreateTenantUsingPOSTParamsBodyCustomPropertiesItems0
*/
type CreateTenantUsingPOSTParamsBodyCustomPropertiesItems0 struct {

	// A unique identifier of a custom property. Is defined by the user. This field is an immutable.
	// Required: true
	Key *string `json:"key"`

	// Value of the custom property.
	// Required: true
	Value *string `json:"value"`
}

// Validate validates this create tenant using p o s t params body custom properties items0
func (o *CreateTenantUsingPOSTParamsBodyCustomPropertiesItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateKey(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateTenantUsingPOSTParamsBodyCustomPropertiesItems0) validateKey(formats strfmt.Registry) error {

	if err := validate.Required("key", "body", o.Key); err != nil {
		return err
	}

	return nil
}

func (o *CreateTenantUsingPOSTParamsBodyCustomPropertiesItems0) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", o.Value); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateTenantUsingPOSTParamsBodyCustomPropertiesItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateTenantUsingPOSTParamsBodyCustomPropertiesItems0) UnmarshalBinary(b []byte) error {
	var res CreateTenantUsingPOSTParamsBodyCustomPropertiesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
