// Code generated by go-swagger; DO NOT EDIT.

package tenants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateCustomPropertyForTenantParams creates a new CreateCustomPropertyForTenantParams object
// with the default values initialized.
func NewCreateCustomPropertyForTenantParams() *CreateCustomPropertyForTenantParams {
	var ()
	return &CreateCustomPropertyForTenantParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateCustomPropertyForTenantParamsWithTimeout creates a new CreateCustomPropertyForTenantParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateCustomPropertyForTenantParamsWithTimeout(timeout time.Duration) *CreateCustomPropertyForTenantParams {
	var ()
	return &CreateCustomPropertyForTenantParams{

		timeout: timeout,
	}
}

// NewCreateCustomPropertyForTenantParamsWithContext creates a new CreateCustomPropertyForTenantParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateCustomPropertyForTenantParamsWithContext(ctx context.Context) *CreateCustomPropertyForTenantParams {
	var ()
	return &CreateCustomPropertyForTenantParams{

		Context: ctx,
	}
}

// NewCreateCustomPropertyForTenantParamsWithHTTPClient creates a new CreateCustomPropertyForTenantParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateCustomPropertyForTenantParamsWithHTTPClient(client *http.Client) *CreateCustomPropertyForTenantParams {
	var ()
	return &CreateCustomPropertyForTenantParams{
		HTTPClient: client,
	}
}

/*CreateCustomPropertyForTenantParams contains all the parameters to send to the API endpoint
for the create custom property for tenant operation typically these are written to a http.Request
*/
type CreateCustomPropertyForTenantParams struct {

	/*Request
	  Specification of the custom property that will be created.

	*/
	Request CreateCustomPropertyForTenantBody
	/*TenantID
	  Unique identifier of a tenant.

	*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create custom property for tenant params
func (o *CreateCustomPropertyForTenantParams) WithTimeout(timeout time.Duration) *CreateCustomPropertyForTenantParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create custom property for tenant params
func (o *CreateCustomPropertyForTenantParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create custom property for tenant params
func (o *CreateCustomPropertyForTenantParams) WithContext(ctx context.Context) *CreateCustomPropertyForTenantParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create custom property for tenant params
func (o *CreateCustomPropertyForTenantParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create custom property for tenant params
func (o *CreateCustomPropertyForTenantParams) WithHTTPClient(client *http.Client) *CreateCustomPropertyForTenantParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create custom property for tenant params
func (o *CreateCustomPropertyForTenantParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the create custom property for tenant params
func (o *CreateCustomPropertyForTenantParams) WithRequest(request CreateCustomPropertyForTenantBody) *CreateCustomPropertyForTenantParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the create custom property for tenant params
func (o *CreateCustomPropertyForTenantParams) SetRequest(request CreateCustomPropertyForTenantBody) {
	o.Request = request
}

// WithTenantID adds the tenantID to the create custom property for tenant params
func (o *CreateCustomPropertyForTenantParams) WithTenantID(tenantID string) *CreateCustomPropertyForTenantParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the create custom property for tenant params
func (o *CreateCustomPropertyForTenantParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateCustomPropertyForTenantParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Request); err != nil {
		return err
	}

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
