// Code generated by go-swagger; DO NOT EDIT.

package tenants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetTenantsUsingGETReader is a Reader for the GetTenantsUsingGET structure.
type GetTenantsUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTenantsUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTenantsUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetTenantsUsingGETBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTenantsUsingGETOK creates a GetTenantsUsingGETOK with default headers values
func NewGetTenantsUsingGETOK() *GetTenantsUsingGETOK {
	return &GetTenantsUsingGETOK{}
}

/*GetTenantsUsingGETOK handles this case with default header values.

Successfully returned tenants.
*/
type GetTenantsUsingGETOK struct {
	Payload []*GetTenantsUsingGETOKBodyItems0
}

func (o *GetTenantsUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /v1/tenants][%d] getTenantsUsingGETOK  %+v", 200, o.Payload)
}

func (o *GetTenantsUsingGETOK) GetPayload() []*GetTenantsUsingGETOKBodyItems0 {
	return o.Payload
}

func (o *GetTenantsUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTenantsUsingGETBadRequest creates a GetTenantsUsingGETBadRequest with default headers values
func NewGetTenantsUsingGETBadRequest() *GetTenantsUsingGETBadRequest {
	return &GetTenantsUsingGETBadRequest{}
}

/*GetTenantsUsingGETBadRequest handles this case with default header values.

HTTP request is malformed.
*/
type GetTenantsUsingGETBadRequest struct {
	Payload *GetTenantsUsingGETBadRequestBody
}

func (o *GetTenantsUsingGETBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/tenants][%d] getTenantsUsingGETBadRequest  %+v", 400, o.Payload)
}

func (o *GetTenantsUsingGETBadRequest) GetPayload() *GetTenantsUsingGETBadRequestBody {
	return o.Payload
}

func (o *GetTenantsUsingGETBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetTenantsUsingGETBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetTenantsUsingGETBadRequestBody Response
swagger:model GetTenantsUsingGETBadRequestBody
*/
type GetTenantsUsingGETBadRequestBody struct {

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this get tenants using g e t bad request body
func (o *GetTenantsUsingGETBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetTenantsUsingGETBadRequestBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("getTenantsUsingGETBadRequest"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetTenantsUsingGETBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetTenantsUsingGETBadRequestBody) UnmarshalBinary(b []byte) error {
	var res GetTenantsUsingGETBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetTenantsUsingGETOKBodyItems0 TenantBean
swagger:model GetTenantsUsingGETOKBodyItems0
*/
type GetTenantsUsingGETOKBodyItems0 struct {

	// A set of user defined properties represented as key value pair.
	CustomProperties []*GetTenantsUsingGETOKBodyItems0CustomPropertiesItems0 `json:"customProperties"`

	// The unique identifier of the tenant generated by the system and unique across platform tenant. This field is immutable.
	// Read Only: true
	ID string `json:"id,omitempty"`

	// The name of the tenant.
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this get tenants using g e t o k body items0
func (o *GetTenantsUsingGETOKBodyItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCustomProperties(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetTenantsUsingGETOKBodyItems0) validateCustomProperties(formats strfmt.Registry) error {

	if swag.IsZero(o.CustomProperties) { // not required
		return nil
	}

	for i := 0; i < len(o.CustomProperties); i++ {
		if swag.IsZero(o.CustomProperties[i]) { // not required
			continue
		}

		if o.CustomProperties[i] != nil {
			if err := o.CustomProperties[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("customProperties" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetTenantsUsingGETOKBodyItems0) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", o.Name); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetTenantsUsingGETOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetTenantsUsingGETOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res GetTenantsUsingGETOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetTenantsUsingGETOKBodyItems0CustomPropertiesItems0 CustomPropertyBean
swagger:model GetTenantsUsingGETOKBodyItems0CustomPropertiesItems0
*/
type GetTenantsUsingGETOKBodyItems0CustomPropertiesItems0 struct {

	// A unique identifier of a custom property. Is defined by the user. This field is an immutable.
	// Required: true
	Key *string `json:"key"`

	// Value of the custom property.
	// Required: true
	Value *string `json:"value"`
}

// Validate validates this get tenants using g e t o k body items0 custom properties items0
func (o *GetTenantsUsingGETOKBodyItems0CustomPropertiesItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateKey(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetTenantsUsingGETOKBodyItems0CustomPropertiesItems0) validateKey(formats strfmt.Registry) error {

	if err := validate.Required("key", "body", o.Key); err != nil {
		return err
	}

	return nil
}

func (o *GetTenantsUsingGETOKBodyItems0CustomPropertiesItems0) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", o.Value); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetTenantsUsingGETOKBodyItems0CustomPropertiesItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetTenantsUsingGETOKBodyItems0CustomPropertiesItems0) UnmarshalBinary(b []byte) error {
	var res GetTenantsUsingGETOKBodyItems0CustomPropertiesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
