// Code generated by go-swagger; DO NOT EDIT.

package tenants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetGatewayRegistrationP12CertificateUsingGETParams creates a new GetGatewayRegistrationP12CertificateUsingGETParams object
// with the default values initialized.
func NewGetGatewayRegistrationP12CertificateUsingGETParams() *GetGatewayRegistrationP12CertificateUsingGETParams {
	var ()
	return &GetGatewayRegistrationP12CertificateUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetGatewayRegistrationP12CertificateUsingGETParamsWithTimeout creates a new GetGatewayRegistrationP12CertificateUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetGatewayRegistrationP12CertificateUsingGETParamsWithTimeout(timeout time.Duration) *GetGatewayRegistrationP12CertificateUsingGETParams {
	var ()
	return &GetGatewayRegistrationP12CertificateUsingGETParams{

		timeout: timeout,
	}
}

// NewGetGatewayRegistrationP12CertificateUsingGETParamsWithContext creates a new GetGatewayRegistrationP12CertificateUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetGatewayRegistrationP12CertificateUsingGETParamsWithContext(ctx context.Context) *GetGatewayRegistrationP12CertificateUsingGETParams {
	var ()
	return &GetGatewayRegistrationP12CertificateUsingGETParams{

		Context: ctx,
	}
}

// NewGetGatewayRegistrationP12CertificateUsingGETParamsWithHTTPClient creates a new GetGatewayRegistrationP12CertificateUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetGatewayRegistrationP12CertificateUsingGETParamsWithHTTPClient(client *http.Client) *GetGatewayRegistrationP12CertificateUsingGETParams {
	var ()
	return &GetGatewayRegistrationP12CertificateUsingGETParams{
		HTTPClient: client,
	}
}

/*GetGatewayRegistrationP12CertificateUsingGETParams contains all the parameters to send to the API endpoint
for the get gateway registration p12 certificate using g e t operation typically these are written to a http.Request
*/
type GetGatewayRegistrationP12CertificateUsingGETParams struct {

	/*TenantID
	  Unique identifier of tenant.

	*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get gateway registration p12 certificate using g e t params
func (o *GetGatewayRegistrationP12CertificateUsingGETParams) WithTimeout(timeout time.Duration) *GetGatewayRegistrationP12CertificateUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get gateway registration p12 certificate using g e t params
func (o *GetGatewayRegistrationP12CertificateUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get gateway registration p12 certificate using g e t params
func (o *GetGatewayRegistrationP12CertificateUsingGETParams) WithContext(ctx context.Context) *GetGatewayRegistrationP12CertificateUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get gateway registration p12 certificate using g e t params
func (o *GetGatewayRegistrationP12CertificateUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get gateway registration p12 certificate using g e t params
func (o *GetGatewayRegistrationP12CertificateUsingGETParams) WithHTTPClient(client *http.Client) *GetGatewayRegistrationP12CertificateUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get gateway registration p12 certificate using g e t params
func (o *GetGatewayRegistrationP12CertificateUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTenantID adds the tenantID to the get gateway registration p12 certificate using g e t params
func (o *GetGatewayRegistrationP12CertificateUsingGETParams) WithTenantID(tenantID string) *GetGatewayRegistrationP12CertificateUsingGETParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the get gateway registration p12 certificate using g e t params
func (o *GetGatewayRegistrationP12CertificateUsingGETParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *GetGatewayRegistrationP12CertificateUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
