// Code generated by go-swagger; DO NOT EDIT.

package protocols

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateProtocolUsingPOSTReader is a Reader for the CreateProtocolUsingPOST structure.
type CreateProtocolUsingPOSTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateProtocolUsingPOSTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateProtocolUsingPOSTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateProtocolUsingPOSTOK creates a CreateProtocolUsingPOSTOK with default headers values
func NewCreateProtocolUsingPOSTOK() *CreateProtocolUsingPOSTOK {
	return &CreateProtocolUsingPOSTOK{}
}

/*CreateProtocolUsingPOSTOK handles this case with default header values.

OK
*/
type CreateProtocolUsingPOSTOK struct {
	Payload *CreateProtocolUsingPOSTOKBody
}

func (o *CreateProtocolUsingPOSTOK) Error() string {
	return fmt.Sprintf("[POST /v1/protocols][%d] createProtocolUsingPOSTOK  %+v", 200, o.Payload)
}

func (o *CreateProtocolUsingPOSTOK) GetPayload() *CreateProtocolUsingPOSTOKBody {
	return o.Payload
}

func (o *CreateProtocolUsingPOSTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreateProtocolUsingPOSTOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*CreateProtocolUsingPOSTBody ProtocolBean
swagger:model CreateProtocolUsingPOSTBody
*/
type CreateProtocolUsingPOSTBody struct {

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this create protocol using p o s t body
func (o *CreateProtocolUsingPOSTBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreateProtocolUsingPOSTBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateProtocolUsingPOSTBody) UnmarshalBinary(b []byte) error {
	var res CreateProtocolUsingPOSTBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*CreateProtocolUsingPOSTOKBody ProtocolBean
swagger:model CreateProtocolUsingPOSTOKBody
*/
type CreateProtocolUsingPOSTOKBody struct {

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this create protocol using p o s t o k body
func (o *CreateProtocolUsingPOSTOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreateProtocolUsingPOSTOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateProtocolUsingPOSTOKBody) UnmarshalBinary(b []byte) error {
	var res CreateProtocolUsingPOSTOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
