// Code generated by go-swagger; DO NOT EDIT.

package protocols

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateProtocolUsingPOSTParams creates a new CreateProtocolUsingPOSTParams object
// with the default values initialized.
func NewCreateProtocolUsingPOSTParams() *CreateProtocolUsingPOSTParams {
	var ()
	return &CreateProtocolUsingPOSTParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateProtocolUsingPOSTParamsWithTimeout creates a new CreateProtocolUsingPOSTParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateProtocolUsingPOSTParamsWithTimeout(timeout time.Duration) *CreateProtocolUsingPOSTParams {
	var ()
	return &CreateProtocolUsingPOSTParams{

		timeout: timeout,
	}
}

// NewCreateProtocolUsingPOSTParamsWithContext creates a new CreateProtocolUsingPOSTParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateProtocolUsingPOSTParamsWithContext(ctx context.Context) *CreateProtocolUsingPOSTParams {
	var ()
	return &CreateProtocolUsingPOSTParams{

		Context: ctx,
	}
}

// NewCreateProtocolUsingPOSTParamsWithHTTPClient creates a new CreateProtocolUsingPOSTParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateProtocolUsingPOSTParamsWithHTTPClient(client *http.Client) *CreateProtocolUsingPOSTParams {
	var ()
	return &CreateProtocolUsingPOSTParams{
		HTTPClient: client,
	}
}

/*CreateProtocolUsingPOSTParams contains all the parameters to send to the API endpoint
for the create protocol using p o s t operation typically these are written to a http.Request
*/
type CreateProtocolUsingPOSTParams struct {

	/*Request
	  request

	*/
	Request CreateProtocolUsingPOSTBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create protocol using p o s t params
func (o *CreateProtocolUsingPOSTParams) WithTimeout(timeout time.Duration) *CreateProtocolUsingPOSTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create protocol using p o s t params
func (o *CreateProtocolUsingPOSTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create protocol using p o s t params
func (o *CreateProtocolUsingPOSTParams) WithContext(ctx context.Context) *CreateProtocolUsingPOSTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create protocol using p o s t params
func (o *CreateProtocolUsingPOSTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create protocol using p o s t params
func (o *CreateProtocolUsingPOSTParams) WithHTTPClient(client *http.Client) *CreateProtocolUsingPOSTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create protocol using p o s t params
func (o *CreateProtocolUsingPOSTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the create protocol using p o s t params
func (o *CreateProtocolUsingPOSTParams) WithRequest(request CreateProtocolUsingPOSTBody) *CreateProtocolUsingPOSTParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the create protocol using p o s t params
func (o *CreateProtocolUsingPOSTParams) SetRequest(request CreateProtocolUsingPOSTBody) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *CreateProtocolUsingPOSTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Request); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
