// Code generated by go-swagger; DO NOT EDIT.

package capabilities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteCapabilityUsingDELETEParams creates a new DeleteCapabilityUsingDELETEParams object
// with the default values initialized.
func NewDeleteCapabilityUsingDELETEParams() *DeleteCapabilityUsingDELETEParams {
	var ()
	return &DeleteCapabilityUsingDELETEParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCapabilityUsingDELETEParamsWithTimeout creates a new DeleteCapabilityUsingDELETEParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteCapabilityUsingDELETEParamsWithTimeout(timeout time.Duration) *DeleteCapabilityUsingDELETEParams {
	var ()
	return &DeleteCapabilityUsingDELETEParams{

		timeout: timeout,
	}
}

// NewDeleteCapabilityUsingDELETEParamsWithContext creates a new DeleteCapabilityUsingDELETEParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteCapabilityUsingDELETEParamsWithContext(ctx context.Context) *DeleteCapabilityUsingDELETEParams {
	var ()
	return &DeleteCapabilityUsingDELETEParams{

		Context: ctx,
	}
}

// NewDeleteCapabilityUsingDELETEParamsWithHTTPClient creates a new DeleteCapabilityUsingDELETEParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteCapabilityUsingDELETEParamsWithHTTPClient(client *http.Client) *DeleteCapabilityUsingDELETEParams {
	var ()
	return &DeleteCapabilityUsingDELETEParams{
		HTTPClient: client,
	}
}

/*DeleteCapabilityUsingDELETEParams contains all the parameters to send to the API endpoint
for the delete capability using d e l e t e operation typically these are written to a http.Request
*/
type DeleteCapabilityUsingDELETEParams struct {

	/*CapabilityID
	  Unique identifier of a capability.

	*/
	CapabilityID string
	/*TenantID
	  Unique identifier of a tenant.

	*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete capability using d e l e t e params
func (o *DeleteCapabilityUsingDELETEParams) WithTimeout(timeout time.Duration) *DeleteCapabilityUsingDELETEParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete capability using d e l e t e params
func (o *DeleteCapabilityUsingDELETEParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete capability using d e l e t e params
func (o *DeleteCapabilityUsingDELETEParams) WithContext(ctx context.Context) *DeleteCapabilityUsingDELETEParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete capability using d e l e t e params
func (o *DeleteCapabilityUsingDELETEParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete capability using d e l e t e params
func (o *DeleteCapabilityUsingDELETEParams) WithHTTPClient(client *http.Client) *DeleteCapabilityUsingDELETEParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete capability using d e l e t e params
func (o *DeleteCapabilityUsingDELETEParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCapabilityID adds the capabilityID to the delete capability using d e l e t e params
func (o *DeleteCapabilityUsingDELETEParams) WithCapabilityID(capabilityID string) *DeleteCapabilityUsingDELETEParams {
	o.SetCapabilityID(capabilityID)
	return o
}

// SetCapabilityID adds the capabilityId to the delete capability using d e l e t e params
func (o *DeleteCapabilityUsingDELETEParams) SetCapabilityID(capabilityID string) {
	o.CapabilityID = capabilityID
}

// WithTenantID adds the tenantID to the delete capability using d e l e t e params
func (o *DeleteCapabilityUsingDELETEParams) WithTenantID(tenantID string) *DeleteCapabilityUsingDELETEParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the delete capability using d e l e t e params
func (o *DeleteCapabilityUsingDELETEParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCapabilityUsingDELETEParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param capabilityId
	if err := r.SetPathParam("capabilityId", o.CapabilityID); err != nil {
		return err
	}

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
