// Code generated by go-swagger; DO NOT EDIT.

package session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCurrentUserUsingGETParams creates a new GetCurrentUserUsingGETParams object
// with the default values initialized.
func NewGetCurrentUserUsingGETParams() *GetCurrentUserUsingGETParams {

	return &GetCurrentUserUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCurrentUserUsingGETParamsWithTimeout creates a new GetCurrentUserUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCurrentUserUsingGETParamsWithTimeout(timeout time.Duration) *GetCurrentUserUsingGETParams {

	return &GetCurrentUserUsingGETParams{

		timeout: timeout,
	}
}

// NewGetCurrentUserUsingGETParamsWithContext creates a new GetCurrentUserUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCurrentUserUsingGETParamsWithContext(ctx context.Context) *GetCurrentUserUsingGETParams {

	return &GetCurrentUserUsingGETParams{

		Context: ctx,
	}
}

// NewGetCurrentUserUsingGETParamsWithHTTPClient creates a new GetCurrentUserUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCurrentUserUsingGETParamsWithHTTPClient(client *http.Client) *GetCurrentUserUsingGETParams {

	return &GetCurrentUserUsingGETParams{
		HTTPClient: client,
	}
}

/*GetCurrentUserUsingGETParams contains all the parameters to send to the API endpoint
for the get current user using g e t operation typically these are written to a http.Request
*/
type GetCurrentUserUsingGETParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get current user using g e t params
func (o *GetCurrentUserUsingGETParams) WithTimeout(timeout time.Duration) *GetCurrentUserUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get current user using g e t params
func (o *GetCurrentUserUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get current user using g e t params
func (o *GetCurrentUserUsingGETParams) WithContext(ctx context.Context) *GetCurrentUserUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get current user using g e t params
func (o *GetCurrentUserUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get current user using g e t params
func (o *GetCurrentUserUsingGETParams) WithHTTPClient(client *http.Client) *GetCurrentUserUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get current user using g e t params
func (o *GetCurrentUserUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCurrentUserUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
